### ISSUE TITLE
Wrong Permissions of uploaded files

### ISSUE THREAD

**Issue by wucherpfennig** [thephpleague/flysystem-bundle#113]
Hello everybody

I am not able to make uploads publicly available. I am using the [VichUploaderBundle](https://github.com/dustin10/VichUploaderBundle) and uploads / delete etc. work just fine. 

However the permissions of the uploaded folder are not correct. Folders are always getting the permission `0700` which results in inaccessible file.

currently I am using the following configuration:

```yaml
flysystem:
    storages:
        asset_remote.storage:
            adapter: 'sftp'
            visibility: 'public'
            options:
                host: 'redacted'
                port: 1234
                username: 'user'
                password: 'password'
                root: '/some/path'
```

I think this problem is related to the option `Config::OPTION_DIRECTORY_VISIBILITY` (see: https://github.com/thephpleague/flysystem-sftp-v3/blob/e7d0d30a886d6aaa89a33e45b45718629ba434e6/SftpAdapter.php#L119).

This option is never set therefore it will mark the folders always as private.

--- Update
I have update the configuration with the change suggested above. It won't work.

Also adding the following configuration options do not work:

```yaml
                directoryPerm: 0777
                permPublic: 0777
                permPrivate: 0777
```

---update

However while changing this line https://github.com/thephpleague/flysystem-sftp/blob/253731e91081d9dc1cd582bb9bf051e58156c1b4/SftpAdapter.php#L123

```php
        //$this->makeDirectory($parentDirectory, $visibility);
        $this->makeDirectory($parentDirectory, 'public');
```

it works. Therefore I do assume that there is a config issue? 

Any suggestions are very much welcome ;-)
