### ISSUE TITLE
How to use Cloudflare R2 cloud storage?

### ISSUE THREAD

**Issue by nicodemuz** [thephpleague/flysystem-bundle#116]
Cloudflare R2 is suppousedly S3 compatible. However, when I try to configure to use R2, I get the following message:
```
The XML you provided was not well formed or did not validate against our published schema.
```

**Comment by nicodemuz** [comment]
Nevermind, I got it working using a config similar to:
```
services:
    cloudflare_r2_client:
        class: 'AsyncAws\S3\S3Client'
        arguments:
            -  endpoint: 'https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com'
               accessKeyId: 'YOUR_KEY_ID'
               accessKeySecret: 'YOUR_KEY_SECRET'

flysystem:
    storages:
        default.storage:
            adapter: 'asyncaws'
            options:
                client: 'cloudflare_r2_client'
                bucket: 'YOUR_BUCKET_NAME'
```
