### ISSUE TITLE
how to get full path

### ISSUE THREAD

**Issue by langziyang** [thephpleague/flysystem-bundle#141]
```
config/packages/flysystem.yaml
flysystem:
    storages:
        sylius.storage:
            adapter: 'local'
            options:
                directory: '%sylius_core.images_dir%'
```
the adapter can be anthing,like local, aws,
```
public function list(Request $request, FilesystemOperator $syliusStorage, FilesystemAdapterInterface $filesystemAdapter)
    {
        $list = $syliusStorage->listContents("",Filesystem::LIST_DEEP);
        return $this->render('@JinberSyliusTinymcePlugin/admin/file/list.html.twig', [
            'finder' => $list
        ]);
    }
```
```
<div class="image_container">
    {% for file in finder %}
        <div class="image_box0">
            {% if file.type is same as 'dir' %}
                {% else %}
                    <img src="{{ asset('/media/image/'~file.path) }}" alt="" class="img img-small"
                         onclick="chooseImage('{{ '/media/image/'~file.path }}')">
            {% endif %}
        </div>
    {% endfor %}
</div>
````
how to get dynamic image src path without '/media/image/',
