### ISSUE TITLE
Default config for adapter "local"

### ISSUE THREAD

**Issue by sdespont** [thephpleague/flysystem-bundle#158]
According to the default config https://github.com/thephpleague/flysystem-bundle/blob/956c039258e3ed44747c8d97f5132e3e9a6d6765/docs/B-configuration-reference.md

the following configuration should be correct
```
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: "%root_dir%"
                visibility: 'public'
                directory_visibility: 'public'
                permissions:
                    file:
                        public: 0o644
                        private: 0o600
                    dir:
                        public: 0o755
                        private: 0o700
```

But throw
`The options "directory_visibility", "visibility" do not exist. Defined options are: "directory", "lazy_root_creation", "lock", "permissions", "skip_links".`

How can I specify the `directory_visibility` option ?
