### ISSUE TITLE
[Usage] When to Install league/flysystem-bundle vs league/flysystem

### ISSUE THREAD

**Issue by cancan101** [thephpleague/flysystem-bundle#166]
This is a usage question / suggestion for doc improvement:

When do I need to (explicitly) install `league/flysystem-bundle` vs `league/flysystem` vs one of the specific adapters (e.g. `league/flysystem-azure-blob-storage`)?

I am using Symfony by way of Pimcore and have set up a `flystem.yaml`:
```yaml
flysystem:
    storages:
        pimcore.asset.storage:
            adapter: azure
```
I am not otherwise directly calling any of the league supplied PHP directly.
