### ISSUE TITLE
Docs: Readability issue when passing constructor args 

### ISSUE THREAD

**Issue by beganovich** [thephpleague/flysystem-bundle#170]
Refers to documentation for creating custom client when using compatible S3 storage.

Link: https://github.com/thephpleague/flysystem-bundle/blob/3.x/docs/2-cloud-storage-providers.md#digitalocean-spaces

I think it's very easy to overlook the fact you have to pass two blank spaces in order for YAML parser to read this correctly.

```yaml
arguments:
     -  endpoint: '%env(DIGITALOCEAN_SPACES_ENDPOINT)%'
```

Proposed solutions.

1:

```yaml
arguments:
     -
         endpoint: '%env(DIGITALOCEAN_SPACES_ENDPOINT)%'
```

2:

```yaml
arguments:
     $configuration:
         endpoint: '%env(DIGITALOCEAN_SPACES_ENDPOINT)%'
```

3:

```yaml
arguments:
     - { endpoint: '%env(DIGITALOCEAN_SPACES_ENDPOINT)%' }
```

Number two is used by some popular packages, such as HWIOAuthBundle (https://github.com/hwi/HWIOAuthBundle/blob/master/docs/3-configuring_the_security_layer.md#a-have-a-user-provider-that-implements-oauthawareuserproviderinterface)

I can send relevant PRs if you agree this is useful.
