### ISSUE TITLE
Switch storage by environment

### ISSUE THREAD

**Issue by anthropos9** [thephpleague/flysystem-bundle#21]
We have a setup where in a testing environment we use local storage, but in stage and prod we're on Azure. (Yes I know this is not ideal, but it's what I've been handed) Is there a way to make the defaultStorage option switch based upon the environment we're working in? Thanks.

**Comment by tgalopin** [comment]
Hello @anthropos9 !

That's actually not a bad idea, not sure why this would be a problem :) . I do this in my applications as well and to achieve it I use Symfony configuration overriding:

``` yaml
# config/packages/flysystem.yaml
# => by default, store on filesystem
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'

# config/packages/test/flysystem.yaml
# => in tests, store in memory
flysystem:
    storages:
        default.storage:
            adapter: 'memory'

# config/packages/prod/flysystem.yaml
# => in production, store in Cloud (here S3, but you can adapt)
services:
    Aws\S3\S3Client:
        arguments:
            - endpoint: 'https://s3.fr-par.scw.cloud'
              version: '2006-03-01'
              region: 'fr-par'
              credentials:
                  key: '%env(S3_STORAGE_KEY)%'
                  secret: '%env(S3_STORAGE_SECRET)%'

flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: 'bucket-name'
```
