### ISSUE TITLE
Azure Too Few Arguements

### ISSUE THREAD

**Issue by anthropos9** [thephpleague/flysystem-bundle#23]
When I try to use Azure as my storage environment I get this error:

> Too few arguments to function MicrosoftAzure\Storage\Common\Internal\ServiceRestProxy::__construct(), 1 passed in /app/var/cache/dev/ContainerHJExcnV/getDefault_StorageService.php on line 9 and at least 3 expected

I'm not sure what I'm doing wrong. Could someone direct me on how to get this connection to work correctly? Thanks

This is my config:
``` 
services:
  MicrosoftAzure\Storage\Blob\BlobRestProxy:
    arguments:
      - connectionString: '%env(AZURE_CONNECTION_STRING)%'

flysystem:
  storages:
     default.storage:
      adapter: 'azure'
      options:
        client: 'MicrosoftAzure\Storage\Blob\BlobRestProxy'
        container: 'container_name'
```

**Comment by anthropos9** [comment]
I think I figured it out. Please let me know if there's a better way of doing it.

config:
``` yaml
services:
  MicrosoftAzure\Storage\Blob\BlobRestProxy:
    factory: ['@App\Factory\AzureClientFactory',createAzureRestProxy]

flysystem:
  default.storage:
      adapter: 'azure'
      options:
        client: 'MicrosoftAzure\Storage\Blob\BlobRestProxy'
        container: 'container_name'
```

factory:
``` php
<?php
namespace App\Factory;

use MicrosoftAzure\Storage\Blob\BlobRestProxy;

class AzureClientFactory
{
    public static function createAzureRestProxy()
    {
        return BlobRestProxy::createBlobService(getenv('AZURE_CONNECTION_STRING'));
    }
}
```

**Comment by tgalopin** [comment]
Hello @anthropos9 !

I think your problem does not come from the bundle but from the initialization of the service. Your second way works fine, but I would suggest a few improvements:

- To rely on Symfony env variables instead of getenv (getenv does not allow you to easily swap the value of the parameter, for instance in tests) ;
- To not use a factory class, it is not necessary here ;

I think your initial issue came from the definition of your service:

```
services:
  MicrosoftAzure\Storage\Blob\BlobRestProxy:
    arguments:
      - connectionString: '%env(AZURE_CONNECTION_STRING)%'
```

This would create a definition with an array as argument: `['connectionString' => '...']`. In your Factory, it does not seem to be what you actually use. I suggest something like:

```
services:
  MicrosoftAzure\Storage\Blob\BlobRestProxy:
    factory: ['MicrosoftAzure\Storage\Blob\BlobRestProxy', 'createBlobService']
    arguments: ['%env(AZURE_CONNECTION_STRING)%']
```

This should work, remove the need for your factory class and use the Symfony `AZURE_CONNECTION_STRING` env variable (which you can define either as a real env var, or using a .env file).
