### ISSUE TITLE
[Question] How can I get the full path to the file?

### ISSUE THREAD

**Issue by ViktorKudlai** [thephpleague/flysystem-bundle#40]
Hi.

I'm using Flysystem-bundle with `local` adapter.
My configuration is:
```
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/samples/'
```
Also, I have created table, where I have file name with extension (e.g. "1.pdf").
I need to pass full path to the frontend but `get()` method, located in the `FilesystemInterface` is **deprecated**. 

How can I do this?
Thanks.

**Comment by AnthonyGWeb** [comment]
Hi @ViktorKudlai,

You have closed your issue, but do you have found a solution to retrieve your full path ? I have the same issue.

Thanks.

**Comment by ViktorKudlai** [comment]
Hi, @AnthonyGWeb.
Here is my configuration.

File - project/config/packages/flysystem.yaml.
```
flysystem:
    storages:
        sample_file.storage:
            adapter: 'local'
            options:
                directory: '%app.fly.sample_file_path%'
```
File - project/config/services.yaml
```
parameters:
    locale: 'en'
    app.fly.sample_file_path: '%env(BASE_PUBLIC_PATH)%/samples/'
```

File - .env
```
###> league/flysystem-bundle ###
# Please, specify full path to the project's public directory.
BASE_PUBLIC_PATH="%kernel.project_dir%/public"
###< league/flysystem-bundle ###
```

File - service/SampleManager.php
```
    public function __construct(
        ParameterBagInterface $parameterBag,
        FilesystemInterface $sampleFileStorage
    ) {
        $this->parameterBag = $parameterBag;
        $this->sampleFileStorage = $sampleFileStorage;
    }

    /**
     * Returns Sample filepath.
     *
     * @throws Exception
     */
    public function getSampleFileFullPath(string $sampleRelativePath): string
    {
        $baseSampleFilePath = $this->parameterBag->get('app.fly.sample_file_path');
        if (! $this->sampleFileStorage->has($sampleRelativePath)) {
            throw new Exception('File not found');
        }

        return $baseSampleFilePath.$sampleRelativePath;
    }

```
