### ISSUE TITLE
[question] access S3Client object from services from within symfony

### ISSUE THREAD

**Issue by waspinator** [thephpleague/flysystem-bundle#42]
I'm using S3 (minio) as my data storage adapter. I set up the server config in the `yaml` file, but I need the `S3Client` object to get temporary pre-signed URLs to files. Is there a way I can get the S3Client used by flysystem to reuse its configuration? On a related note, is there a way to get tempraroy pre-signed URLs from S3 using flysystem directly?

`config/packages/flysystem.yaml`
```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/media'

        images.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: 'images'
                
services:
    Aws\S3\S3Client:
        arguments:
            - endpoint: 'http://minio:9000'
              version: 'latest'
              region: 'us-east-1'
              use_path_style_endpoint: true
              credentials:
                  key: '%env(S3_STORAGE_KEY)%'
                  secret: '%env(S3_STORAGE_SECRET)%'
```

[src/EventSubscriber/ResolveMediaObjectContentUrlSubscriber.php](https://api-platform.com/docs/core/file-upload/#resolving-the-file-url)
```php
public function onPreSerialize(ViewEvent $event): void
{
...
$this->s3 = new S3Client([
            'endpoint' => 'http://localhost:9000',
            'version' => 'latest',
            'region'  => 'us-east-1',
            'use_path_style_endpoint' => true,
            'credentials' => [
                'key'    =>  $_ENV["S3_STORAGE_KEY"],
                'secret' => $_ENV["S3_STORAGE_SECRET"],
            ],
        ]);

$command = $this->s3->getCommand('GetObject', [
    'Bucket' => 'images',
    'Key'    => $mediaObject->file
]);
$preSignedRequest = $this->s3->createPresignedRequest($command, '+10 minutes');
$preSignedUrl =  (string)  $preSignedRequest->getUri();
...
}
```
