### ISSUE TITLE
Default visibility public ACL for object created in a bucket

### ISSUE THREAD

**Issue by tristanbes** [thephpleague/flysystem-bundle#50]
Hello,

Objects created via `VichUploaderBundle` does not allow to change the default visibility, so all objects are created with a private ACL (default).

I remember that 1UpFlysystemBundle has an option for its bundle to set the default visibility for created object; How to achieve that for this bundle ? 

I tried to pass extra options for the storage client, but the visibility option doesn't exist:

```yaml
flysystem:
    storages:
        user.storage.source:
            adapter: 'asyncaws'
            options:
                client: 'async_aws.client.s3'
                bucket: '%env(S3_BUCKET_NAME)%'
                prefix: '/users'
                options:
                    visibility: public-read    <--- doesn't exist :'D 
```

Reference: https://github.com/dustin10/VichUploaderBundle/issues/1149

**Comment by tristanbes** [comment]
Answer:

```
flysystem:
    storages:
        user.storage.source:
            adapter: 'asyncaws'
            visibility: public
            options:
                client: 'async_aws.client.s3'
                bucket: '%env(S3_BUCKET_NAME)%'
                prefix: '/users'
```
