### ISSUE TITLE
Got this stream from `flysystem-bundle` without seekable opportunity

### ISSUE THREAD

**Issue by shubaivan** [thephpleague/flysystem-bundle#53]
I use  [flysystem-bundle](https://github.com/thephpleague/flysystem-bundle) products from the same company `thephpleague`. I got this stream from `flysystem-bundle` without seekable opportunity

```
flysystem:
  storages:
    reaources.storage:
      adapter: 'aws'
      options:
        client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
        bucket: 'minimoj-consumer'
        prefix: 'minimoj'

services:
  Aws\S3\S3Client:
    arguments:
      - endpoint: '%env(S3_END_POINT)%'
        version: 'latest'
        region: 'ams3'
        use_path_style_endpoint: true
        credentials:
          key: '%env(S3_STORAGE_KEY)%'
          secret: '%env(S3_STORAGE_SECRET)%'
```

then 

```
use Keven\Flysystem\Concatenate\Append;
use Keven\Flysystem\Concatenate\Concatenate;
use League\Flysystem\FilesystemInterface;
use League\Flysystem\Util;

class DigitalOceanStorage
{
    private $storage;

    // The variable name $defaultStorage matters: it needs to be the camelized version
    // of the name of your storage.
    public function __construct(FilesystemInterface $reaourcesStorage)
    {
        $reaourcesStorage->addPlugin(new Append());
        $this->storage = $reaourcesStorage;
    }

    /**
     * @return FilesystemInterface
     */
    public function getStorage(): FilesystemInterface
    {
        return $this->storage;
    }
```

and in my service

```
    /**
     * @var DigitalOceanStorage
     */
    private $do;


           .....


            $readStream = $this->do->getStorage()->readStream($filePath);

```

and this is stream not seekable

```
result = {array} [11]
 crypto = {array} [4]
 timed_out = false
 blocked = true
 eof = false
 wrapper_data = {array} [12]
 wrapper_type = "http"
 stream_type = "tcp_socket/ssl"
 mode = "r"
 unread_bytes = {int} 7715
 seekable = false
 uri = "https://minimoj-consumer.ams3.digitaloceanspaces.com/minimoj-consumer/minimoj/download_files/adrecord/gus_textil/20200909163429.csv"
```

How to make my stream seekable ?
from what this is dependencies, rom digital ocean space ?
