### ISSUE TITLE
Wrong default for visibility in yaml configuration

### ISSUE THREAD

**Issue by GameplayJDK** [thephpleague/flysystem-bundle#54]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no (maybe)
| Version     | 1.5.0

#### Summary

I encountered this when using `league/flysystem` (1.0.46) with the available `league/flysystem-bundle` (1.5.0).

In my opinion the default for `visibility` should not be `null`, but `public` instead. Alternatively the configuration node should be marked as required.

```php
                            ->scalarNode('visibility')->defaultNull()->end() // <- This does not seem correct.
                            ->booleanNode('case_sensitive')->defaultTrue()->end()
                            ->booleanNode('disable_asserts')->defaultFalse()->end()
```

This is related to [this issue](https://github.com/thephpleague/flysystem/issues/1201)

#### How to reproduce

Using the following yaml configuration:

```yaml
flysystem:
  storages:
    example.storage:
      adapter: 'local'
      options:
        directory: '%kernel.project_dir%/var/storage/example/storage'

```

Somewhere in my code I'm calling `createDirectory()`. Make sure the directory does not yet exist.

That's caused by the way the default is retrieved. Currently `array_key_exists()` is used to check if the configuration object passed to the adapter method contains such a key. It is empty by default, so the fallback config is asked about that key (`visibility`). The fallback config contains `null` as value. That issue is already described in the linked issue at `league/flysystem`.
