### ISSUE TITLE
LiipImagineBundle Flysystem Resolver 

### ISSUE THREAD

**Issue by angelomelonas** [thephpleague/flysystem-bundle#62]
Does `league/flysystem-bundle` have compatibility with the [LiipImagineBundle](https://github.com/liip/LiipImagineBundle)? According to the [LiipImagineBundle Symfony docs](https://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolver/flysystem.html), we can use [oneup/flysystem-bundle](https://github.com/1up-lab/OneupFlysystemBundle) as a Flysystem Resolver. As we prefer using this bundle instead, I am just curious to know if anyone has manage to use `league/flysystem-bundle` instead of the `Oneup` version.

**Comment by mynameisbogdan** [comment]
I know my response is a little late, but I'll reply for future reference.

Yes, it's compatible. 

```yaml
flysystem:
    storages:
        images.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/media/image'

liip_imagine:
    loaders:
        default:
            flysystem:
                filesystem_service: 'images.storage'
```
