### ISSUE TITLE
Incompatible use of dynamic environment variables "int:FTP_PORT"

### ISSUE THREAD

**Issue by andezr** [thephpleague/flysystem-bundle#7]
_(1/2) InvalidOptionsException
The option "port" with value "%env(int:FTP_PORT)%" is expected to be of type "int", but is of type "string".
 (2/2) EnvParameterException
Incompatible use of dynamic environment variables "int:FTP_PORT" found in parameters._

**.env**
`FTP_PORT=221`

**flysystem.yaml**
```
flysystem:
    storages:
        backup.storage:
            adapter: 'ftp'
            options:
                host: 'ftp.example.com'
                username: 'username'
                password: 'password'
                port: '%env(int:FTP_PORT)%'
                root: '/path/to/root'
                passive: true
                ssl: true
                timeout: 30
```

This is problematic line \League\FlysystemBundle\Adapter\Builder\FtpAdapterDefinitionBuilder::configureOptions:47
`$resolver->setAllowedTypes('port', 'int');`
