### ISSUE TITLE
Wrong URI with aws/aws-sdk-php v3.175.0

### ISSUE THREAD

**Issue by Spomky** [thephpleague/flysystem-bundle#74]
Hi,

I updated my project dependencies and now it is using aws/aws-sdk-php v3.175.0.
Before that version, the URI of the S3 instance was correct (let say https://s3.cloud.app), but with this new version, the URL that is hitted is bucket_name.https://s3.cloud.app which is wrong.

From what I understand, this is caused by [this change](https://github.com/aws/aws-sdk-php/compare/3.174.3...3.175.0) and the new behaviour of [src/S3/BucketEndpointArnMiddleware.php](https://github.com/aws/aws-sdk-php/compare/3.174.3...3.175.0#diff-957b0d8794451a7b2e1450157996fa9f7f8ce8ba3e034979c80aec0ab7beb298R166).

Can you help me fixing this bug. I think this is just something that we need to configure, but I cannot find how from the documentation.
The bundle configuration is as follow:

```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            options:
                client: 's3_client'
                bucket: "%env(S3_BUCKET)%"
```

Many thanks.
Regards.
