### ISSUE TITLE
Cannot build adapter

### ISSUE THREAD

**Issue by dextercampos** [thephpleague/flysystem-bundle#78]
Hello! I'm having trouble building any adapter that uses env variables.

I have this config in `flysystem.yaml`
```
flysystem:
    storages:
        default.storage:
            adapter: 'gcloud'
            options:
                bucket: '%env(GCLOUD_STORAGE_BUCKET)%'
                client: '%env(GCLOUD_CLIENT_ID)%'
```

I get an error:
```
Incompatible use of dynamic environment variables "GCLOUD_CLIENT_ID" found in parameters.
```

I also tried with parameters still no luck
```
parameters:
    gcloud_storage_bucket: '%env(GCLOUD_STORAGE_BUCKET)%'
    gcloud_client_id: '%env(GCLOUD_CLIENT_ID)%'
flysystem:
    storages:
        default.storage:
            adapter: 'gcloud'
            options:
                bucket: '%gcloud_storage_bucket%'
                client: '%gcloud_client_id%'
```
