### ISSUE TITLE
Symfony no longer parses octal numbers starting with 0 alone

### ISSUE THREAD

**Issue by skon-hh** [thephpleague/flysystem-bundle#81]
Starting with Symfony 5.1 following deprecation is triggered:
```bash
php bin/console lint:yaml config --parse-tags
  ERROR  in config/packages/flysystem.yaml
  Since symfony/yaml 5.1: Support for parsing numbers prefixed with 0 as octal numbers. They will be parsed as strings as of 6.0 at line 32 (near "directoryPerm: 0770").
```
The content of `config/packages/flysystem.yaml`:
```yaml
flysystem:
  storages:
    sftp.storage:
      adapter: 'sftp'
      options:
        host: '<host>'
        port: 22
        username: '<user>'
        password: '<password>'
        privateKey: '<privateKey>'
        root: '<root>'
        timeout: 3
        directoryPerm: 0770
```

If I change `0770` to string representation `'0770'` I'm getting wrong directory permissions for newly generated folders on my sftp server. I think the issue is in [SftpAdapterDefinitionBuilder.php](https://github.com/thephpleague/flysystem-bundle/blob/320a440261eef4c711fa3807fde301425625585c/src/Adapter/Builder/SftpAdapterDefinitionBuilder.php#L62), this should allow string values. If understand the code correctly the used library [phpseclib/phpseclib](https://github.com/phpseclib/phpseclib) expects directory permissions to be of type integer.

I'm working with Symfony 5.3 and flysystem-bundle 1.5.0
