### ISSUE TITLE
[FTP Adapter] Using SSL, we get an error : ftp_fput(): SSL_shutdown failed

### ISSUE THREAD

**Issue by fdiedler** [thephpleague/flysystem-bundle#94]
Hi,

I am using Flysystem with the FTP adapter and my configuration is 
```
flysystem:
    storages:
        default.storage:
            adapter: 'ftp'
            options:
                host: ftpupload.net
                username: <username>
                password: <password>
                port: 21
                ssl: true          #seems to bug...
                passive: true
                #ignore_passive_address: true
                root: /myDirectory
```

However, when I upload a file, I got an error : 
> ftp_fput(): SSL_shutdown failed

What is wrong ?

Thanks,
