### ISSUE TITLE
Register a stream wrapper for each registered filesystem

### ISSUE THREAD

**Issue by dkarlovi** [thephpleague/flysystem-bundle#96]
For example

```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
                ```
                
`flysystem+default.storage://foo/bar/bat.csv` points to `%kernel.project_dir%/var/storage/default/foo/bar/bar/csv`.

Similar to https://github.com/twistor/flysystem-stream-wrapper, but up to date.
